# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up
#   + On windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true"

module OS
        def OS.windows?
                (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
        end

        def OS.mac?
                (/darwin/ =~ RUBY_PLATFORM) != nil
        end
        def OS.unix?
                !OS.windows?
        end
        def OS.linux?
                OS.unix? and not OS.mac?
        end
end

Vagrant.configure("2") do |config|
  array = ["odoo", "pgadmin-icwebapp"]        
  array.each_with_index do |val, index|
        config.vm.define "docker-#{val}" do |docker|
             docker.vm.box = "geerlingguy/centos7"
                if OS.linux?
                        docker.vm.network "private_network",  type: "static", ip: "192.168.99.2#{index}", virtualbox__intnet: "08net"
                elsif OS.windows?
                        docker.vm.network "private_network",  type: "static", ip: "192.168.99.2#{index}"
                else
                        puts 'OS not managed'
                end
                docker.vm.hostname = "docker-#{val}"
                docker.vm.provider "virtualbox" do |v|
                        v.name = "docker-#{val}"
                        v.memory = 1024
                        v.cpus = 1
                end
                docker.vm.provision :shell do |shell|
                        shell.path = "install_docker.sh"
                        shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
                end
        end
  end
end
