version: '3.3'
services:
    postgres:
        environment:
            - POSTGRES_USER=odoo_user
            - POSTGRES_PASSWORD=odoo_password
            - POSTGRES_DB=postgres
        networks:
            - ic_network
        volumes:
            - 'pgdata:/var/lib/postgresql/data'
        container_name: postgres
        image: 'postgres:13'
        ports:
            - '5432:5432'
    odoo:
        depends_on:
            - postgres
        ports:
            - '8081:8069'
        container_name: odoo
        networks:
            - ic_network
        volumes:
            - 'odoo-web-data:/var/lib/odoo'
        environment:
            - USER=odoo_user
            - PASSWORD=odoo_password
            - HOST=postgres
        image: odoo:13

volumes:
    odoo-web-data:
    pgdata:
networks:
    ic_network:
      driver: bridge
      name: ic_network
