# -*- mode: ruby -*-
# vi: set ft=ruby :

module OS
  def OS.windows?
          (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end
  def OS.mac?
          (/darwin/ =~ RUBY_PLATFORM) != nil
  end
  def OS.unix?
          !OS.windows?
  end
  def OS.linux?
          OS.unix? and not OS.mac?
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
    if OS.linux?
      # Sous linux, il FAUT préciser le nom du réseau hôte
      # https://www.vagrantup.com/docs/providers/virtualbox/networking
      # Dans Virtualbox > Fichier > Gestionnaire de réseau hôte (CTRL + H):
      # - Vérifier la présence de vboxnet0, sinon le créer
      # - Vérifier l'adresse IPv4 et le masque, sinon les modifier (à faire 2 fois pour être pris en compte)
      #
      # Vérifier avec "ip -a" le nom, l'IP et le masque
      jenkins.vm.network "private_network",  type: "static", ip: "192.168.99.13", name: "vboxnet0"
    elsif OS.windows?
      jenkins.vm.network "private_network",  type: "static", ip: "192.168.99.13"
    else
        puts 'OS not managed'
    end
    jenkins.vm.hostname = "docker-jenkins"
    jenkins.vm.provider "virtualbox" do |v|
      v.name = "docker-jenkins"
      v.memory = 2048
      v.cpus = 2
    end
    jenkins.vm.provision :shell do |shell|
      shell.path = "install_docker.sh"
      shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
    jenkins.vm.provision :shell do |shell|
      shell.privileged = false
      shell.path = "install_docker_jenkins.sh"
    end
  end
end
